package com.pltm.dto;

public class Mail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.id
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.mail_acc
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    private String mailAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.mail_auth
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    private String mailAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.username
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.mail_host_name
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    private String mailHostName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.id
     *
     * @return the value of mail.id
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.id
     *
     * @param id the value for mail.id
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.mail_acc
     *
     * @return the value of mail.mail_acc
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public String getMailAcc() {
        return mailAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.mail_acc
     *
     * @param mailAcc the value for mail.mail_acc
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public void setMailAcc(String mailAcc) {
        this.mailAcc = mailAcc == null ? null : mailAcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.mail_auth
     *
     * @return the value of mail.mail_auth
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public String getMailAuth() {
        return mailAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.mail_auth
     *
     * @param mailAuth the value for mail.mail_auth
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public void setMailAuth(String mailAuth) {
        this.mailAuth = mailAuth == null ? null : mailAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.username
     *
     * @return the value of mail.username
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.username
     *
     * @param username the value for mail.username
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.mail_host_name
     *
     * @return the value of mail.mail_host_name
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public String getMailHostName() {
        return mailHostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.mail_host_name
     *
     * @param mailHostName the value for mail.mail_host_name
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public void setMailHostName(String mailHostName) {
        this.mailHostName = mailHostName == null ? null : mailHostName.trim();
    }
}