package com.pltm.dto;

import java.util.ArrayList;
import java.util.List;

public class MailHostExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public MailHostExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHostNameIsNull() {
            addCriterion("host_name is null");
            return (Criteria) this;
        }

        public Criteria andHostNameIsNotNull() {
            addCriterion("host_name is not null");
            return (Criteria) this;
        }

        public Criteria andHostNameEqualTo(String value) {
            addCriterion("host_name =", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotEqualTo(String value) {
            addCriterion("host_name <>", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameGreaterThan(String value) {
            addCriterion("host_name >", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameGreaterThanOrEqualTo(String value) {
            addCriterion("host_name >=", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameLessThan(String value) {
            addCriterion("host_name <", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameLessThanOrEqualTo(String value) {
            addCriterion("host_name <=", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameLike(String value) {
            addCriterion("host_name like", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotLike(String value) {
            addCriterion("host_name not like", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameIn(List<String> values) {
            addCriterion("host_name in", values, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotIn(List<String> values) {
            addCriterion("host_name not in", values, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameBetween(String value1, String value2) {
            addCriterion("host_name between", value1, value2, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotBetween(String value1, String value2) {
            addCriterion("host_name not between", value1, value2, "hostName");
            return (Criteria) this;
        }

        public Criteria andSmtpHostIsNull() {
            addCriterion("smtp_host is null");
            return (Criteria) this;
        }

        public Criteria andSmtpHostIsNotNull() {
            addCriterion("smtp_host is not null");
            return (Criteria) this;
        }

        public Criteria andSmtpHostEqualTo(String value) {
            addCriterion("smtp_host =", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostNotEqualTo(String value) {
            addCriterion("smtp_host <>", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostGreaterThan(String value) {
            addCriterion("smtp_host >", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostGreaterThanOrEqualTo(String value) {
            addCriterion("smtp_host >=", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostLessThan(String value) {
            addCriterion("smtp_host <", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostLessThanOrEqualTo(String value) {
            addCriterion("smtp_host <=", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostLike(String value) {
            addCriterion("smtp_host like", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostNotLike(String value) {
            addCriterion("smtp_host not like", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostIn(List<String> values) {
            addCriterion("smtp_host in", values, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostNotIn(List<String> values) {
            addCriterion("smtp_host not in", values, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostBetween(String value1, String value2) {
            addCriterion("smtp_host between", value1, value2, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostNotBetween(String value1, String value2) {
            addCriterion("smtp_host not between", value1, value2, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortIsNull() {
            addCriterion("smtp_host_port is null");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortIsNotNull() {
            addCriterion("smtp_host_port is not null");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortEqualTo(String value) {
            addCriterion("smtp_host_port =", value, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortNotEqualTo(String value) {
            addCriterion("smtp_host_port <>", value, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortGreaterThan(String value) {
            addCriterion("smtp_host_port >", value, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortGreaterThanOrEqualTo(String value) {
            addCriterion("smtp_host_port >=", value, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortLessThan(String value) {
            addCriterion("smtp_host_port <", value, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortLessThanOrEqualTo(String value) {
            addCriterion("smtp_host_port <=", value, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortLike(String value) {
            addCriterion("smtp_host_port like", value, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortNotLike(String value) {
            addCriterion("smtp_host_port not like", value, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortIn(List<String> values) {
            addCriterion("smtp_host_port in", values, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortNotIn(List<String> values) {
            addCriterion("smtp_host_port not in", values, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortBetween(String value1, String value2) {
            addCriterion("smtp_host_port between", value1, value2, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andSmtpHostPortNotBetween(String value1, String value2) {
            addCriterion("smtp_host_port not between", value1, value2, "smtpHostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostIsNull() {
            addCriterion("pop3_host is null");
            return (Criteria) this;
        }

        public Criteria andPop3HostIsNotNull() {
            addCriterion("pop3_host is not null");
            return (Criteria) this;
        }

        public Criteria andPop3HostEqualTo(String value) {
            addCriterion("pop3_host =", value, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostNotEqualTo(String value) {
            addCriterion("pop3_host <>", value, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostGreaterThan(String value) {
            addCriterion("pop3_host >", value, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostGreaterThanOrEqualTo(String value) {
            addCriterion("pop3_host >=", value, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostLessThan(String value) {
            addCriterion("pop3_host <", value, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostLessThanOrEqualTo(String value) {
            addCriterion("pop3_host <=", value, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostLike(String value) {
            addCriterion("pop3_host like", value, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostNotLike(String value) {
            addCriterion("pop3_host not like", value, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostIn(List<String> values) {
            addCriterion("pop3_host in", values, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostNotIn(List<String> values) {
            addCriterion("pop3_host not in", values, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostBetween(String value1, String value2) {
            addCriterion("pop3_host between", value1, value2, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostNotBetween(String value1, String value2) {
            addCriterion("pop3_host not between", value1, value2, "pop3Host");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortIsNull() {
            addCriterion("pop3_host_port is null");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortIsNotNull() {
            addCriterion("pop3_host_port is not null");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortEqualTo(String value) {
            addCriterion("pop3_host_port =", value, "pop3HostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortNotEqualTo(String value) {
            addCriterion("pop3_host_port <>", value, "pop3HostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortGreaterThan(String value) {
            addCriterion("pop3_host_port >", value, "pop3HostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortGreaterThanOrEqualTo(String value) {
            addCriterion("pop3_host_port >=", value, "pop3HostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortLessThan(String value) {
            addCriterion("pop3_host_port <", value, "pop3HostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortLessThanOrEqualTo(String value) {
            addCriterion("pop3_host_port <=", value, "pop3HostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortLike(String value) {
            addCriterion("pop3_host_port like", value, "pop3HostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortNotLike(String value) {
            addCriterion("pop3_host_port not like", value, "pop3HostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortIn(List<String> values) {
            addCriterion("pop3_host_port in", values, "pop3HostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortNotIn(List<String> values) {
            addCriterion("pop3_host_port not in", values, "pop3HostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortBetween(String value1, String value2) {
            addCriterion("pop3_host_port between", value1, value2, "pop3HostPort");
            return (Criteria) this;
        }

        public Criteria andPop3HostPortNotBetween(String value1, String value2) {
            addCriterion("pop3_host_port not between", value1, value2, "pop3HostPort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mail_host
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 19 23:50:15 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mail_host
     *
     * @mbggenerated Mon Mar 19 23:50:15 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}